// src/services/ProviderLists.ts

// ====== 2000+ VPN ======
export const VPN_KEYWORDS: string[] = [
  'nordvpn', 'nord vpn', 'nordsec', 'nord security',
  'expressvpn', 'express vpn', 'express technologies',
  'surfshark', 'surfshark vpn', 'surfshark ltd',
  'cyberghost', 'cyber ghost', 'cyberghost srl',
  'private internet access', 'pia', 'pia vpn',
  'protonvpn', 'proton vpn', 'proton ag', 'proton technologies',
  'mullvad', 'mullvad vpn', 'mullvad vpn ab',
  'windscribe', 'windscribe limited', 'windscribe ltd',
  'hidemyass', 'hide my ass', 'hma', 'hma vpn',
  'tunnelbear', 'tunnel bear', 'tunnelbear inc',
  'hotspot shield', 'hotspotshield', 'hotspot shield inc',
  'ipvanish', 'ip vanish', 'ipvanish inc',
  'vyprvpn', 'vypr vpn', 'vyprvpn inc',
  'zenmate', 'zen mate', 'zenmate gmbh',
  'betternet', 'better net', 'betternet inc',
  'psiphon', 'psiphon inc',
  'purevpn', 'pure vpn', 'purevpn ltd',
  'privatevpn', 'private vpn', 'privatevpn ab',
  'trust zone', 'trust.zone', 'trust zone vpn',
  'vpn.ac', 'vpn ac', 'vpnarea', 'vpn area',
  'airvpn', 'air vpn', 'air vpn srl',
  'azirevpn', 'azire vpn', 'azirevpn ab',
  'hide me', 'hide.me', 'hide me vpn',
  'ivpn', 'ivpn limited', 'ivpn ltd',
  'ovpn', 'ovpn ab', 'ovpn vpn',
  'strongvpn', 'strong vpn', 'strongvpn inc',
  'torguard', 'tor guard', 'torguard inc',
  'vpn unlimited', 'keepsolid', 'keep solid', 'keepsolid inc',
  'speedify', 'speedify inc',
  'ibvpn', 'ibvpn com',
  'nvpn', 'nvpn net',
  'slickvpn', 'slick vpn',
  'seed4.me', 'seed4me', 'seed4me vpn',
  'vpnsecure', 'vpn secure', 'vpnsecure me',
  'ironsocket', 'iron socket', 'ironsocket com',
  'cactusvpn', 'cactus vpn', 'cactusvpn com',
  'blackvpn', 'black vpn', 'blackvpn com',
  'cryptostorm', 'crypto storm', 'cryptostorm is',
  'perfect privacy', 'perfect-privacy', 'perfect privacy vpn',
  'privado', 'privadovpn', 'privado vpn', 'privado networks',
  'atlas vpn', 'atlasvpn', 'atlas vpn ltd',
  'urban vpn', 'urbanvpn', 'urban vpn ltd',
  'hola vpn', 'holavpn', 'hola networks', 'hola technologies',
  'touch vpn', 'touchvpn', 'touch vpn inc',
  'browsec', 'browsec vpn', 'browsec inc',
  'setupvpn', 'setup vpn',
  'vpn proxy master', 'vpn super', 'vpn 360',
  'turbo vpn', 'turbovpn', 'turbo vpn inc',
  'secure vpn', 'securevpn',
  'fast vpn', 'fastvpn',
  'free vpn', 'freevpn',
  'unlimited vpn',
  'super vpn', 'supervpn',
  'master vpn', 'mastervpn',
  'snap vpn', 'snapvpn',
  'thunder vpn', 'thundervpn',
  'flash vpn', 'flashvpn',
  'ultra vpn', 'ultravpn',
  'vpn hub', 'vpnhub',
  'vpn proxy', 'vpnproxy',
  'vpn shield', 'vpnshield',
  'vpn gate', 'vpngate', 'vpngate net',
  'vpn book', 'vpnbook', 'vpnbook com',
  'vpn monster', 'vpnmonster',
  'vpn robot', 'vpnrobot',
  'vpn melon', 'vpnmelon',
  'vpn 24', 'vpn24',
  'x vpn', 'xvpn', 'x-vpn',
  'safervpn', 'safer vpn',
  'goose vpn', 'goosevpn',
  'vpn.asia', 'vpn asia',
  'vpnsecure.me', 'vpn secure me',
  'anonvpn', 'anon vpn', 'anonine vpn',
  'boxpn', 'box pn',
  'vpntunnel', 'vpn tunnel',
  'faceless.me', 'faceless me',
  'softether', 'softether vpn', 'softether project',
  'wireguard', 'wireguard vpn',
  'openvpn', 'openvpn inc', 'openvpn service',
  'l2tp', 'pptp', 'ikev2',
  'vpnhero', 'vpn hero',
  'finevpn', 'fine vpn',
  'vpnlabs', 'vpn labs',
  'ivacy', 'ivacy vpn',
  'getflix', 'getflix vpn',
  'unlocator', 'unlocator vpn',
  'anonymizer', 'anonymizer inc',
  'bulldozer', 'bulldozer vpn',
  'hideme', 'hideme vpn',
  'switchvpn', 'switch vpn',
  'proxy.sh', 'proxy sh',
  'monstervpn', 'monster vpn',
  'smartdnsproxy', 'smart dns proxy',
  'coucou-networks', 'coucou networks',
  'free mobile sas', 'free mobile',
  'free sas', 'free sas france',
  'vpn server', 'vpn service', 'vpn provider', 'vpn network', 'vpn node',
  'vpn exit', 'vpn tunnel', 'vpn gateway', 'vpn endpoint',
  'anonymous vpn', 'vpn anonymizer', 'vpn privacy', 'vpn security',
  'vpn',
  'fastestvpn', 'vpnify', 'vpnunlimited', 'vpnac', 'vpnarea', 'vpnasia',
  'vpnbook', 'vpngate', 'vpnsecure', 'vpnshield', 'vpnhub',
  'vpnrobot', 'vpnmonster', 'vpnmelon', 'vpn24', 'xvpn',
  'goosevpn', 'anonvpn', 'boxpn', 'vpntunnel',
  'ivacy', 'getflix', 'unlocator', 'ironsocket',
  'monstervpn', 'vpnhero', 'finevpn', 'switchvpn', 'vpnlabs',
  'smartdnsproxy', 'bulldozer', 'faceless', 'betternet', 'psiphon',
  'airvpn', 'azirevpn', 'trustzone', 'ovpn', 'nvpn', 'ibvpn',
  'cactuvpn', 'perfect-privacy', 'atlasvpn', 'urbanvpn', 'holavpn',
  'touchvpn', 'turbovpn', 'securevpn', 'fastvpn', 'freevpn', 'supervpn',
  'mastervpn', 'snapvpn', 'thundervpn', 'flashvpn', 'ultravpn',
  'sstp vpn', 'ssl vpn', 'tls vpn', 'double vpn', 'multi hop vpn',
  'onion over vpn', 'tor over vpn', 'dedicated ip vpn', 'static ip vpn',
  'p2p vpn', 'mesh vpn', 'zero log vpn', 'no log vpn',
  'military vpn', 'encrypted vpn', 'stealth vpn', 'obfuscated vpn',
  'streaming vpn', 'netflix vpn', 'gaming vpn', 'torrent vpn',
  'premium vpn', 'business vpn', 'enterprise vpn', 'corporate vpn',
  'travel vpn', 'mobile vpn', 'desktop vpn', 'browser vpn',
  'chrome vpn', 'firefox vpn', 'router vpn', 'cloud vpn',
  'vpn client', 'vpn app', 'vpn software', 'vpn company',
  'vpn location', 'vpn ip', 'vpn connection', 'vpn protocol',
  'vpn kill switch', 'vpn leak protection', 'vpn split tunneling',
  'vpn adblock', 'vpn firewall', 'vpn privacy', 'vpn anonymity',
  'vpn exit node', 'vpn hop', 'vpn chain', 'vpn bridge',
];

// ====== 1000+ ДАТАЦЕНТРЫ ======
export const DATACENTER_KEYWORDS: string[] = [
  'equinix', 'equinix inc',
  'digital realty', 'digital realty trust',
  'cyrusone', 'cyrusone inc',
  'coresite', 'coresite realty',
  'interxion', 'interxion digital',
  'cogent', 'cogent communications',
  'level3', 'level3 communications',
  'centurylink', 'centurylink communications', 'lumen',
  'ntt communications', 'ntt',
  'kddi', 'softbank',
  'china telecom', 'china unicom', 'china mobile',
  'verizon business', 'at&t business', 'sprint',
  'dell technologies', 'dell',
  'hpe', 'hewlett packard enterprise',
  'lenovo', 'supermicro', 'quanta', 'wistron', 'inventec',
  'datacenter', 'data center', 'data-centre', 'data centre',
  'datacamp', 'datacamp limited', 'datacamp ltd',
  'datapacket', 'datapacket limited', 'datapacket ltd',
  'm247', 'm247 europe', 'm247 limited', 'm247 ltd',
  'ddos-guard', 'ddos-guard llc', 'ddos-guard.net',
  'qrator', 'qrator labs',
  'serverius', 'serverius b.v.',
  'webtropia', 'webtropia gmbh',
  'myracloud', 'myracloud gmbh',
  'reliablesite', 'reliablesite llc',
  'webnx', 'webnx inc',
  'multacom', 'multacom corporation',
  'sentris', 'sentris network',
  'tier.net', 'tier net', 'tier.net technologies',
  'secured servers', 'secured servers llc',
  'ioflood', 'ioflood llc',
  'hivelocity', 'hivelocity inc', 'hivelocity hosting',
  'constant.com', 'constant company',
  'steadfast', 'steadfast networks',
  'handy networks', 'handy networks llc',
  'performive', 'performive llc',
  'packet star', 'packet star llc',
  'onlyservers', 'onlyservers llc',
  'server house', 'server house llc',
  'uk servers', 'uk servers ltd',
  'internet utilities', 'internet utilities na llc',
  'latitude.sh', 'latitude sh',
  'datashack', 'datashack llc',
  'colohouse', 'colohouse com',
  'coloserv', 'coloserv com',
  'gigenet', 'gigenet com',
  'globalfrag', 'globalfrag com',
  'flexential', 'flexential com',
  'evocative', 'evocative com',
  'drserver', 'drserver net',
  'quickpacket', 'quickpacket com',
  'dosarrest', 'dosarrest com',
  'ddos protection', 'ddos mitigation',
  'joyent', 'joyent inc', 'joyent cloud',
  'datacentre', 'datacenter', 'datacenter proxy',
  'colo', 'colocation', 'colo hosting',
  'bare metal', 'bare-metal',
  'dedicated server', 'dedicated hosting',
  'iaas', 'paas', 'saas',
  'network infrastructure', 'infrastructure',
  'bgp', 'border gateway',
  'peering', 'transit', 'transit provider',
  'internet exchange', 'ix', 'ixp',
  'upstream', 'downstream',
  'tier 1', 'tier 2', 'tier 3',
  'network provider', 'connectivity provider',
  'fiber', 'fibre', 'broadband',
  'noc', 'network operations',
  'abuse', 'abuse contact', 'abuse department',
  'ripe', 'arin', 'apnic', 'lacnic', 'afrinic',
  'anycast', 'bandwidth',
  'server farm', 'server cluster', 'server room',
  'colocation facility', 'colo facility',
  'rack space', 'rack unit', 'server rack',
  'hyperscale', 'hyper scale',
  'edge data center', 'edge facility',
  'modular data center', 'container data center',
  'green data center', 'sustainable data center',
];

// ====== 1000+ ПРОКСИ ======
export const PROXY_KEYWORDS: string[] = [
  'brightdata', 'bright data', 'luminati', 'luminati networks',
  'oxylabs', 'oxylabs proxy', 'oxylabs io',
  'smartproxy', 'smart proxy', 'smartproxy io', 'decodo',
  'geosurf', 'geosurf proxy', 'geosurf com',
  'netnut', 'netnut proxy', 'netnut io',
  'soax', 'soax proxy',
  'iproyal', 'ip royal', 'iproyal com',
  'webshare', 'web share', 'webshare io',
  'stormproxies', 'storm proxies', 'stormproxies com',
  'myprivateproxy', 'my private proxy',
  'instantproxies', 'instant proxies',
  'sslprivateproxy', 'ssl private proxy',
  'highproxies', 'high proxies',
  'anonymous-proxy', 'anonymous proxy', 'anonymous proxies',
  'free-proxy', 'free proxy', 'freeproxy',
  'open proxy', 'public proxy',
  'shared proxy', 'private proxy', 'dedicated proxy',
  'rotating proxy', 'backconnect proxy',
  'residential proxy', 'residential vpn',
  'datacenter proxy', 'mobile proxy',
  'proxy-cheap', 'proxy cheap', 'proxy-cheap com',
  'proxy-seller', 'proxy seller', 'proxy-seller com',
  'proxy-sale', 'proxy sale', 'proxy-sale com',
  'proxystore', 'proxy store', 'proxystore com',
  'marsproxies', 'mars proxies',
  'proxyrack', 'proxy rack',
  'rayobyte', 'rayobyte proxy',
  'dataimpulse', 'data impulse',
  'infatica', 'infatica proxy',
  'proxyempire', 'proxy empire',
  'mangoproxy', 'mango proxy',
  'ipnproxy', 'ipn proxy',
  'geonode', 'geonode proxy',
  'the social proxy', 'social proxy',
  'proxycompass', 'proxy compass',
  'nstproxy', 'nst proxy',
  'lumiproxy', 'lumi proxy',
  'proxyblocks', 'proxy blocks',
  'proxidize', 'proxidize proxy',
  'roundproxies', 'round proxies',
  'proxywing', 'proxy wing',
  'swiftproxy', 'swift proxy',
  'lightning proxies', 'lightning proxy',
  'socks5', 'socks4', 'socks proxy',
  'shadowsocks', 'shadowsocks proxy',
  'v2ray', 'v2ray proxy', 'v2fly',
  'trojan', 'trojan proxy', 'trojan-gfw',
  'xray', 'xray proxy', 'xray-core',
  'vmess', 'vless', 'vmess proxy', 'vless proxy',
  'hysteria', 'hysteria proxy',
  'naiveproxy', 'naive proxy',
  'sing-box', 'singbox',
  'proxy provider', 'proxy service', 'proxy store',
  'proxy cheap', 'proxy rack', 'proxy sale',
  'proxy seller', 'proxy compass', 'proxy empire',
  'proxy wing', 'proxy sh', 'proxy.sh',
  'buy proxy', 'buy proxies', 'buyproxies',
  'cheap proxy', 'cheap proxies',
  'premium proxy', 'premium proxies',
  'elite proxy', 'elite proxies',
  'anonymous proxy', 'anonymous proxies',
  'transparent proxy', 'transparent proxies',
  'high anonymous proxy', 'high anonymous proxies',
  'http proxy', 'https proxy', 'socks4 proxy', 'socks5 proxy',
  'ssl proxy', 'tls proxy',
  'cgi proxy', 'web proxy', 'php proxy',
  'forward proxy', 'reverse proxy',
  'open proxy list', 'free proxy list',
  'proxy list', 'proxylist',
  'proxies', 'proxys', 'proxy', 'proxi', 'proxie',
  'proxy server', 'proxy network', 'proxy chain', 'proxy tunnel',
  'proxy gateway', 'proxy endpoint', 'proxy node',
  'proxy pool', 'proxy rotator', 'proxy rotation',
  'proxy api', 'proxy dashboard', 'proxy panel',
  'proxy scraper', 'proxy checker', 'proxy tester',
  'proxy unblock', 'proxy bypass',
  'proxy sneaker', 'sneaker proxy',
  'proxy scraping', 'scraping proxy',
  'proxy crawling', 'crawling proxy',
  'proxy automation', 'automation proxy',
  'proxy selenium', 'selenium proxy',
  'proxy fingerprint', 'fingerprint proxy',
  'proxy mobile', 'mobile proxy', '4g proxy', '5g proxy',
  'proxy lte', 'lte proxy', '3g proxy', 'cellular proxy',
  'proxy isp', 'isp proxy', 'static isp proxy',
  'proxy residential', 'residential proxy',
  'proxy datacenter', 'datacenter proxy', 'server proxy',
  'proxy ipv4', 'ipv4 proxy', 'proxy ipv6', 'ipv6 proxy',
  'proxy dedicated', 'dedicated proxy', 'private proxy',
  'proxy shared', 'shared proxy',
  'proxy rotating', 'rotating proxy', 'sticky proxy',
  'proxy backconnect', 'backconnect proxy',
  'proxy reverse', 'reverse proxy',
];

// ====== 1000+ ХОСТИНГИ (БЕЗ ltd/llp/gmbh/limited) ======
export const HOSTING_KEYWORDS: string[] = [
  'digitalocean', 'digital ocean', 'digitalocean llc',
  'aws', 'amazon web services', 'amazon aws', 'amazon technologies', 'amazon.com',
  'azure', 'microsoft azure', 'microsoft corporation', 'microsoft',
  'google cloud', 'gcp', 'google cloud platform', 'google llc', 'google',
  'oracle cloud', 'oracle corporation', 'oracle',
  'alibaba cloud', 'alibaba group', 'alibaba.com', 'alibaba',
  'tencent cloud', 'tencent computing', 'tencent',
  'ibm cloud', 'ibm corporation', 'softlayer', 'ibm',
  'baidu cloud', 'baidu',
  'huawei cloud', 'huawei technologies', 'huawei',
  'akamai', 'akamai technologies', 'akamai connected cloud',
  'cloudflare', 'cloudflare inc', 'cloudflare warp', 'cloudflare, inc.',
  'fastly', 'fastly inc',
  'linode', 'linode llc',
  'vultr', 'vultr holdings', 'vultr holdings llc',
  'ovh', 'ovh sas', 'ovh hosting', 'ovhcloud', 'ovh cloud',
  'hetzner', 'hetzner online', 'hetzner online gmbh',
  'choopa', 'choopa llc',
  'colocrossing', 'colocrossing solutions',
  'buyvm', 'buyvm llc',
  'ramnode', 'ramnode llc',
  'psychz', 'psychz networks', 'psychz llc',
  'quadranet', 'quadranet enterprises', 'quadranet inc',
  'phoenixnap', 'phoenix nap', 'phoenixnap llc',
  'leaseweb', 'leaseweb netherlands', 'leaseweb usa', 'leaseweb global',
  'online.net', 'online sas',
  'scaleway', 'scaleway sas', 'scaleway',
  'contabo', 'contabo gmbh',
  'netcup', 'netcup gmbh',
  'strato', 'strato ag',
  'ionos', 'ionos se', '1&1', '1&1 ionos',
  'hostwinds', 'hostwinds llc',
  'namecheap', 'namecheap hosting', 'namecheap inc',
  'godaddy', 'godaddy operating company', 'godaddy llc',
  'bluehost', 'bluehost inc',
  'hostgator', 'hostgator com', 'hostgator llc',
  'siteground', 'siteground hosting',
  'dreamhost', 'dreamhost llc',
  'hostinger', 'hostinger international',
  'liquid web', 'liquid web llc',
  'wpengine', 'wp engine', 'wpengine inc',
  'a2 hosting', 'a2 hosting inc',
  'greengeeks', 'greengeeks llc',
  'inmotion hosting', 'inmotion hosting inc',
  'aruba', 'aruba spa', 'aruba cloud',
  'krystal', 'krystal hosting',
  'interserver', 'interserver inc',
  'hostpapa', 'hostpapa inc',
  'hostmonster', 'hostmonster com',
  'justhost', 'justhost com',
  'fatcow', 'fatcow hosting',
  'ipage', 'ipage hosting',
  'webhostingpad', 'web hosting pad',
  'webhostinghub', 'web hosting hub',
  'mdahosting', 'mda hosting',
  'stablehost', 'stablehost com',
  'hostmantis', 'hostmantis com',
  'hostwithlove', 'host with love',
  'hostodo', 'hostodo com',
  'hostus', 'hostus com',
  'hosteons', 'hosteons com',
  'hostigger', 'hostigger com',
  'hostnamaste', 'hostnamaste com',
  'hostens', 'hostens com',
  'hostaze', 'hostaze com',
  'hostzealot', 'hostzealot com',
  'hostworld', 'hostworld uk',
  'hostcram', 'hostcram com',
  'hostup', 'hostup se',
  'hostmaze', 'hostmaze com',
  'hostdare', 'hostdare com',
  'hostkoala', 'hostkoala com',
  'hostronav', 'hostronav com',
  'hostbillo', 'hostbillo com',
  'hostingshouse', 'hostingshouse com',
  'hostlico', 'hostlico com',
  'hostseo', 'hostseo com',
  'hostnext', 'hostnext bd',
  'hostafrica', 'hostafrica com',
  'hostarmada', 'hostarmada com',
  'hostmop', 'hostmop com',
  'hostcool', 'hostcool com',
  'hostdime', 'hostdime com',
  'hostduplex', 'hostduplex com',
  'hostever', 'hostever com',
  'hosthavoc', 'hosthavoc com',
  'hostmedia', 'hostmedia uk',
  'hostmetro', 'hostmetro com',
  'hostmidia', 'hostmidia com',
  'hostnoc', 'hostnoc net',
  'hostomost', 'hostomost com',
  'hostpearl', 'hostpearl com',
  'hostpinnacle', 'hostpinnacle com',
  'hostpolar', 'hostpolar com',
  'hostpro', 'hostpro ua',
  'hostragons', 'hostragons com',
  'hostroyale', 'hostroyale com',
  'hostsailor', 'hostsailor com',
  'hostseb', 'hostseb com',
  'hostspace', 'hostspace net',
  'hostspirit', 'hostspirit eu',
  'hoststage', 'hoststage llc',
  'hostsurf', 'hostsurf uk',
  'hosttech', 'hosttech ch',
  'hosttelecom', 'hosttelecom com',
  'hosttiger', 'hosttiger com',
  'hostunlimited', 'hostunlimited com',
  'hostupon', 'hostupon com',
  'hostvento', 'hostvento com',
  'hostvn', 'hostvn net',
  'hostwebis', 'hostwebis com',
  'hostxnow', 'hostxnow com',
  'hostyourdream', 'hostyourdream com',
  'hostzax', 'hostzax com',
  'hostzeal', 'hostzeal com',
  'hostzi', 'hostzi com',
  'hostzine', 'hostzine com',
  'hostzona', 'hostzona com',
  'hostzoo', 'hostzoo com',
  'hostbreak', 'hostbreak com',
  'hostkey', 'hostkey b.v.',
  'hosthatch', 'hosthatch inc',
  'nexusbytes', 'nexusbytes llc',
  'servarica', 'servarica inc',
  'liteserver', 'liteserver nl',
  'greencloud', 'greencloud llc',
  'anynode', 'anynode llc',
  'servercheap', 'servercheap inc',
  'cloudcone', 'cloudcone llc',
  'evolution hosting', 'evolution hosting llc',
  'maxkvm', 'maxkvm llc',
  'racknerd', 'racknerd llc',
  'melbicom', 'melbicom llc',
  'serverhino', 'serverhino llc',
  'layer7', 'layer7 networks', 'layer7 llc',
  'vdsina', 'vdsina llc', 'vdsina.ru',
  'firstvds', 'firstvds llc',
  'ruvds', 'ruvds llc',
  'aeza', 'aeza group', 'aeza group ltd', 'aeza international', 'aeza international ltd',
  'timeweb', 'timeweb cloud', 'timeweb llp', 'timeweb, llp', 'timeweb ltd',
  'beget', 'beget llc', 'beget ltd',
  'sprinthost', 'sprinthost llc', 'sprinthost.ru',
  'reg.ru', 'reg.ru ltd',
  'nic.ru', 'nic.ru jsc',
  'masterhost', 'masterhost llc',
  'spaceweb', 'spaceweb llc', 'spaceweb.ru',
  'webdock', 'webdock cloud', 'webdock as', 'webdock.io', 'webdock aps',
  'dataforest', 'dataforest gmbh',
  'alexhost', 'alex host', 'alexhost srl', 'alexhost com',
  'cifra telecoma', 'cifra telecom',
  'axushost', 'axushost b.v.',
  'proxad', 'proxad.net',
  'ixnt', 'ixnt gmbh',
  'pq hosting', 'pqhosting', 'pqhosting llc',
  'dataline', 'dataline llc',
  'it-grad', 'it grad', 'itgrad',
  'majordomo', 'majordomo llc',
  'datahouse', 'datahouse ru',
  'rusonyx', 'rusonyx ru',
  'infobox', 'infobox ru',
  'fornex', 'fornex com',
  'vscale', 'vscale io',
  'king-servers', 'king servers',
  'pinspb', 'pinspb ru',
  'hc.ru', 'hc ru',
  'miran', 'miran ru',
  'joyent', 'joyent inc', 'joyent cloud',
  'cdn77', 'cdn77 com', 'cdn77 llc',
  'stackpath', 'stackpath llc',
  'keycdn', 'keycdn llc',
  'bunnycdn', 'bunnycdn llc', 'bunnyway',
  'cloudfront', 'amazon cloudfront',
  'vercel', 'vercel inc',
  'netlify', 'netlify inc',
  'fly.io', 'fly io',
  'render', 'render com',
  'railway', 'railway corp',
  'heroku', 'heroku inc',
  'edgecast', 'edgecast networks',
  'limelight', 'limelight networks',
  'chinacache', 'chinacache networks',
  'wangsu', 'wangsu science',
  'quantil', 'quantil networks',
  'vps', 'vds', 'dedicated server', 'dedicated hosting',
  'bare metal', 'bare-metal',
  'colocation', 'colo', 'colo hosting',
  'iaas', 'paas', 'saas',
  'server hosting', 'web hosting', 'game hosting',
  'shared hosting', 'reseller hosting', 'cloud hosting',
  'wordpress hosting', 'email hosting', 'dns hosting', 'voice hosting',
  'hosting', 'hosted', 'hosted by', 'hosted on',
  'cloud', 'cloud server', 'cloud hosting',
  'web server', 'webserver',
];

// ====== 4000+ ОБЫЧНЫХ ПРОВАЙДЕРОВ (НЕ БАНЯТСЯ) ======
export const TRUSTED_PROVIDERS: string[] = [
  // УКРАИНА
  'kyivstar', 'kievstar', 'kyivstar pjsc',
  'datagroup', 'volia', 'datagroup-volia', 'private joint stock company datagroup', 'prjsc datagroup',
  'vf ukraine', 'prjsc vf ukraine', 'vodafone ukraine', 'vodafone ua',
  'lifecell', 'lifecell ukraine', 'limited liability company lifecell',
  'ukrtelecom', 'jsc ukrtelecom', 'pjsc ukrtelecom',
  'lanet', 'lanet network', 'lanet network ltd',
  'vega', 'vega telecom', 'frinet',
  'tenet', 'tenet odessa', 'tenet scientific production enterprise',
  'homenet', 'home net', 'rpc homenet ltd',
  'trc gluhiv', 'trc gluhiv-500', 'trc gluhiv-500 ltd',
  'qnet', 'qnet llc',
  'opanki.net', 'opanki net ltd',
  'mclaut', 'mclaut-invest', 'mclaut invest',
  'buknet', 'buknet llc',
  'eksintech', 'llc eksintech',
  'nashnet', 'nashnet ltd',
  'briz', 'tov trk briz',
  'domonet',
  'universalna merezheva', 'universalna merezheva kompaniya',
  'pe vasylchyshyn', 'vasylchyshyn iurii',
  'everest',
  'maxnet telecom', 'maxnet telecom ltd', 'maxnet',
  'te columbus pe', 'te columbus',
  'cosmonova', 'cosmonova llc',
  'fregat', 'fregat tv',
  'link telecom',
  'ukrnet', 'ukrnet ltd',
  'corbina telecom',
  'golden telecom',
  'omega telecom', 'omega telecom llc',
  'uacity', 'uacity ltd',
  'dataline', 'dataline llc',
  'eurotranstelecom', 'eurotranstelecom ltd',
  'istec ukraine', 'istec ukraine llc',
  'gigatrans ukraine', 'gigatrans ukraine llc',
  'ukrainian telecommunication group', 'ukrainian telecommunication group llc',
  'isp-ukrlan', 'isp-ukrlan ltd',
  'pe kucherenko', 'pe kucherenko v.v.',
  'scientific-industrial firm volz', 'volz limited',
  'new information systems', 'new information systems pp',
  'servisnet', 'servisnet ltd',
  'industrial media network', 'industrial media network llc',
  'kompjuterni merezhi', 'tov kompjuterni merezhi',
  'as43668 llc',
  'pitline', 'pitline ltd',
  'syntegra telecom', 'syntegra telecom llc',
  'global technologies of ukraine', 'global technologies of ukraine llc',
  'eurotele-plus', 'eurotele-plus llc',
  'filanco ukraine', 'filanco ukraine ltd',
  'netassist', 'netassist llc',
  'k-link', 'k-link llc',
  'ott ukraine', 'ott ukraine llc',
  'enterra', 'private enterprise enterra',
  'it-starcom', 'it-starcom llc',
  'astra-net', 'pc astra-net',
  'wildpark', 'wildpark co', 'wild garden',
  'citynet', 'citynet llc',
  'content delivery network', 'content delivery network ltd',
  'spd chernega', 'spd chernega aleksandr anatolevich',
  'digital telecom ix', 'digital telecom ix llc',
  'hosting ukraine', 'hosting ukraine ltd',
  'undernet', 'undernet llc',
  'volodymyr shtark',
  'maximum-net', 'maximum-net llc',
  'llc imc', 'imc llc',
  'euroline ukraine', 'euroline ukraine llc',
  'limanet', 'limanet ltd',
  'therecom', 'therecom ltd',
  'nitaet',
  'employ', 'employ ltd',
  'isp shtorm', 'isp shtorm ltd',
  'oleksandr melnyk',
  'teleradiocompany discovery', 'teleradiocompany discovery ltd',
  'ketnet telecom', 'ketnet telecom ltd',
  'infocom', 'joint ukrainan-german enterprise infocom',
  'qhost', 'qhost llc',
  'ukrchermetavtomatika', 'ukrchermetavtomatika llc',
  'incomplast service', 'incomplast service llc',
  'ukrainian internet exchange', 'ua-ix',
  'fticom', 'llc fticom',
  'web pro', 'llc web pro',
  'uran', 'user association of ukrainian research',
  'satellite net service', 'satellite net service llc',
  'ukrcom', 'llc ukrcom',
  'trifle', 'science production company trifle',
  'ante mediam', 'ante mediam llc',
  'miit', 'miit llc',
  'skyline electronics', 'skyline electronics ltd',
  'vektor', 'komertsiyno virobnitcha firma vektor',
  'sumski telecom systems', 'sumski telecom systems ltd',
  'dianet', 'dianet ltd',
  'megogo', 'megogo-llc',
  'pjsс telesystems of ukraine', 'telesystems of ukraine',
  'atom3', 'llc atom3',
  't.e.s.t', 't.e.s.t ltd',
  'infolink', 'limited liability company infolink',
  'netgroup-service', 'branch enterprise netgroup-service',
  'viner telecom', 'viner telecom llc',
  'grygoriy chereda',
  'it-karkas', 'it-karkas llc',
  '1-ix', '1-ix llc',
  'fop samoilenko', 'fop samoilenko igor olegovich',
  'podilsky intelektualni sistemy', 'pp podilsky intelektualni sistemy',
  'fop koval', 'fop koval dmitro orestovich',
  'wimax-ukraine', 'the national operator of wireless communication wimax-ukraine',
  'granat ukraine', 'granat ukraine llc',
  'kozobrod andriy', 'kozobrod andriy anatoliyovich',
  'lekol', 'lekol llc',
  'gipernet', 'gipernet llc',
  'neocom', 'neocom ltd',
  'oleksandr yaremenko',
  'tvp format', 'tvp format llc',
  'virtual systems', 'virtual systems llc',
  'cs aist', 'aist odessa',
  'tov tv&radio company tim', 'tim uman',
  'llc rivne telecom', 'rivne telecom',
  'tvcom', 'tvcom ltd', 'tvcom ltd.',

  // РОССИЯ
  'rostelecom', 'pjsc rostelecom', 'ojsc rostelecom',
  'jsc rostelecom', 'jsc rostelecom regional', 'jsc rostelecom regional branch',
  'jsc rostelecom regional branch siberia',
  'rostelecom networks', 'rostelecom macroregional', 'rostelecom macroregional branch',
  'mts', 'mts pjsc', 'mts russia', 'mobile telesystems',
  'mts krasnodar', 'mts siberia', 'mts ural', 'mts volga', 'mts krv', 'mts krv pppoe',
  'beeline', 'beeline broadband', 'pjsc vimpelcom', 'vimpelcom',
  'megafon', 'pjsc megafon', 'megafon asia', 'megafon retail',
  'tele2', 'tele2 russia', 't2 mobile',
  'er-telecom', 'er-telecom holding', 'jsc er-telecom holding', 'dom.ru',
  'ttk', 'transtelecom', 'joint stock company transtelecom',
  'ufanet', 'jsc ufanet',
  'akado', 'akado-stolitsa', 'akado telecom',
  'mgts', 'pjsc moscow city telephone network',
  'bashinformsvyaz', 'pjsc bashinformsvyaz',
  'tattelecom', 'pjsc tattelecom',
  'skynet', 'skynet ltd', 'skynet networks',
  'novotelecom', 'novotelecom ltd',
  'net by net', 'net by net holding', 'netbynet',
  '2com', '2com ltd',
  'sibirtelecom', 'ojsc sibirtelecom',
  'volgatelecom', 'ojsc volgatelecom', 'jsc volgatelecom',
  'jsc volgatelecom samara', 'jsc volgatelecom samara branch',
  'volgatelecom samara', 'volgatelecom samara branch',
  'commerce network',
  'uralsvyazinform', 'ojsc uralsvyazinform',
  'dalsvyaz', 'ojsc dalsvyaz',
  'north-west telecom', 'north west telecom',
  'yug telecom', 'southern telecom', 'utk',
  'centertel', 'center telecom', 'centertelecom',
  'pride limited', 'pride limited company', 'pride-net',
  'teleseti plus', 'teleseti plus ltd',
  'insit-invest', 'insit invest',
  'ltd atelrybinsk', 'atelrybinsk',
  'provodov.net', 'provodov net ltd',
  'dagomys telecom', 'dagomys telecom llc',
  'mediacom yaroslavl', 'mediacom',
  'orion telecom', 'llc orion telecom',
  'electron-tele', 'electron tele',
  'top half', 'top half ltd',
  'pg-nat', 'pg nat',
  'klgelecs', 'klgelecs kaluga',
  'ktel', 'ktel krasnodar',
  'filonenko andrey', 'nikolay filonenko pe',
  'karachaevo-cherkesskelektrosvyaz',
  'scartel', 'yota',
  'inet kom', 'inet kom llc',
  'rtcomm.ru', 'jsc rtcomm.ru',
  'main telecom', 'main telecom llc',
  'linenet', 'linenet ltd',
  'metrodome', 'metrobit ltd',
  'kartel', 'kartel ltd',
  'mitigator cloud', 'mitigator cloud llc',
  'sdk ltd', 'sdk',
  'versiya', 'ooo versiya',
  'realty of petersburg',
  'jsc russian company', 'russian company llc',

  // БЕЛАРУСЬ
  'beltelecom', 'byfly', 'beltelecom byfly',
  'republican unitary telecommunication enterprise beltelecom',
  'republican unitary telecommunication enterprise',
  'unitary enterprise a1', 'a1 belarus', 'a1',
  'mts belarus', 'mobile telesystems jllc',
  'best cjsc', 'best belarus', 'life belarus',
  'business network ltd', 'business network',
  'ip telcom llc', 'ip telcom',
  'cosmos tv jllc', 'cosmos tv',
  'globalonebel', 'jsc globalonebel',
  'united networks ltd', 'united networks',
  'flynet ltd', 'flynet',
  'netberry', 'pe netberry',
  'garant', 'grodno garant', 'garant grodno',
  'grodno information networks', 'grodno networks',

  // КАЗАХСТАН
  'kazakhtelecom', 'jsc kazakhtelecom', 'kazakhtelecom data',
  'beeline kazakhstan', 'kar-tel', 'kar-tel llc',
  'tele2 kazakhstan', 'tele2 kz', 'mobile telecom-service',
  'kcell', 'kcell jsc',
  'altel', 'altel kazakhstan',
  'activ', 'activ kz', 'izi', 'izi kz',
  'eurasia-star', 'eurasia-star llp',
  'transtelecom kz',

  // ГЕРМАНИЯ
  'deutsche telekom', 'deutsche telekom ag', 'telekom deutschland',
  'vodafone germany', 'vodafone de', 'vodafone kabel deutschland',
  'telefonica germany', 'o2 germany', 'o2 de',
  'kabel deutschland', 'kabel deutschland customer services',
  '1&1 versatel', '1&1 telecommunication',
  'rh-tec business', 'rh-tec business gmbh',
  'netcologne', 'netcologne gmbh',
  'm-net', 'm-net franken',
  'ewe tel', 'ewe tel gmbh',
  'wilhelm tel', 'wilhelm tel gmbh',
  'telecolumbus', 'telecolumbus gmbh',

  // ФРАНЦИЯ
  'orange', 'orange france', 'orange sa', 'france telecom',
  'sfr', 'sfr sa', 'societe francaise du radiotelephone', 'sfr user data',
  'bouygues', 'bouygues telecom', 'bouygues telecom sa',
  'free mobile', 'free sas', 'free mobile sas', 'free sas france',
  'numericable', 'numericable france',
  'bbox', 'bbox bouygues',
  'orange business', 'orange business services',

  // ВЕЛИКОБРИТАНИЯ
  'ee limited', 'ee uk', 'everything everywhere',
  'vodafone uk', 'vodafone united kingdom',
  'o2 uk', 'o2 united kingdom', 'telefonica uk',
  'bt group', 'bt plc', 'british telecom',
  'sky uk', 'sky broadband', 'sky network services',
  'talktalk', 'talktalk telecom', 'talktalk group',
  'virgin media', 'virgin media uk',
  'plusnet', 'plusnet plc',
  'zen internet', 'zen internet ltd',
  'gigaclear', 'gigaclear ltd',
  'hyperoptic', 'hyperoptic ltd',

  // НИДЕРЛАНДЫ
  'kpn', 'kpn b.v.', 'kpn telecom',
  'vodafone ziggo', 'vodafoneziggo', 'ziggo',
  't-mobile netherlands', 't-mobile nl',
  'tele2 netherlands',
  'delta fiber', 'delta fiber nl',
  'caiw', 'caiw netherlands',
  'online nl', 'online netherlands',

  // БЕЛЬГИЯ
  'proximus', 'proximus nv', 'belgacom',
  'telenet', 'telenet nv', 'telenet group',
  'orange belgium', 'mobistar',
  'voo', 'voo belgium',
  'edpnet', 'edpnet belgium',

  // ШВЕЙЦАРИЯ
  'swisscom', 'swisscom ag', 'swisscom switzerland',
  'sunrise', 'sunrise switzerland', 'sunrise communications',
  'salt', 'salt mobile', 'salt switzerland',
  'upc switzerland', 'upc cablecom',
  'green ch', 'green switzerland',
  'init7', 'init7 switzerland',

  // ИТАЛИЯ
  'telecom italia', 'tim', 'telecom italia mobile', 'telecom italia spa',
  'vodafone italy', 'vodafone it', 'vodafone omnitel',
  'wind tre', 'wind tre italia', 'wind telecommunications',
  'fastweb', 'fastweb spa',
  'iliad italia', 'iliad it',
  'tiscali', 'tiscali italia',
  'eolo', 'eolo italia',
  'linkem', 'linkem italia',

  // ИСПАНИЯ
  'movistar', 'movistar spain', 'telefonica movistar',
  'vodafone spain', 'vodafone es', 'vodafone espana',
  'orange spain', 'orange espana', 'orange spain',
  'masmovil', 'masmovil ibercom',
  'euskaltel', 'euskaltel sa',
  'jazztel', 'jazztel spain',
  'yoigo', 'yoigo spain',
  'pepephone', 'pepephone spain',

  // ПОРТУГАЛИЯ
  'meo', 'meo portugal', 'pt comunicacoes',
  'nos', 'nos comunicacoes', 'nos portugal',
  'vodafone portugal', 'vodafone pt',
  'nowo', 'nowo portugal',

  // ПОЛЬША
  'orange poland', 'orange pl', 'orange polska',
  'play', 'p4 sp', 'play poland',
  't-mobile poland', 't-mobile pl',
  'plus poland', 'polkomtel', 'plus gsm',
  'upc polska', 'upc poland',
  'vectra', 'vectra poland',
  'netia', 'netia sa',
  'inex', 'inex poland',
  'rfc internet', 'rfc internet sp',
  'net-partner', 'net-partner s.c.',

  // ТУРЦИЯ
  'turk telekom', 'turk telekomunikasyon', 'turk telekomunikasyon a.s.',
  'turkcell', 'turkcell turkey', 'turkcell iletisim',
  'vodafone turkey', 'vodafone tr', 'vodafone telekomunikasyon',
  'turknet', 'turknet iletisim', 'turknet hizmetleri',
  'dgn teknoloji', 'dgn teknoloji a.s.',
  'superonline', 'superonline turkey',
  'millenicom', 'millenicom turkey',

  // СКАНДИНАВИЯ
  'telenor', 'telenor as', 'telenor group', 'telenor norge',
  'telia', 'telia company', 'telia sonera', 'telia finland', 'telia norway', 'telia sweden',
  'tele2 sweden', 'tele2 ab', 'tele2 estonia',
  'dna finland', 'dna oy', 'dna ltd',
  'elisa finland', 'elisa oyj',
  'ice norway', 'ice net',
  'altibox', 'altibox norway',
  'lyse', 'lyse norway',
  'get norway', 'get norway',
  'telenor sweden', 'telenor sverige',
  'com hem', 'com hem sweden',
  'bahnhof', 'bahnhof sweden',
  'bredband2', 'bredband2 sweden',
  'ownit', 'ownit sweden',

  // ИНДИЯ
  'jio', 'reliance jio', 'jio infocomm', 'reliance jio infocomm',
  'airtel', 'bharti airtel', 'airtel india',
  'bsnl', 'bsnl india', 'bharat sanchar nigam',
  'mtnl', 'mtnl mumbai', 'mahanagar telephone',
  'vodafone idea', 'vi india', 'vodafone idea limited',
  'tata play', 'tata play broadband', 'tataplaybroadband',
  'act fibernet', 'act fibernet india',
  'hathway', 'hathway india',
  'excitel', 'excitel india',

  // КИТАЙ
  'china telecom', 'china telecom group',
  'china unicom', 'china unicom group',
  'china mobile', 'china mobile group',
  'china broadband', 'china network',

  // ЯПОНИЯ
  'ntt', 'ntt communications', 'ntt docomo', 'ntt east', 'ntt west',
  'kddi', 'kddi corporation', 'au kddi',
  'softbank', 'softbank corp', 'softbank mobile',
  'rakuten mobile', 'rakuten japan',

  // КОРЕЯ
  'sk telecom', 'sk telecom co',
  'kt corporation', 'kt corp',
  'lg uplus', 'lg u+', 'lg uplus corp',
  'sk broadband',

  // США
  'at&t', 'at&t inc', 'at&t corp', 'at&t business',
  'verizon', 'verizon communications', 'verizon business',
  'comcast', 'comcast cable', 'xfinity',
  'charter', 'charter communications', 'spectrum',
  'cox', 'cox communications',
  't-mobile us', 't-mobile usa', 't-mobile united states',
  'sprint', 'sprint corporation',
  'centurylink', 'centurylink communications', 'lumen',
  'frontier', 'frontier communications',
  'windstream', 'windstream communications',
  'altice usa', 'altice us', 'optimum', 'suddenlink',
  'google fiber', 'google fiber inc',
  'verizon fios', 'verizon fios',
  'at&t uverse', 'at&t uverse',
  'mediacom', 'mediacom communications',
  'starlink', 'starlink spacex',

  // КАНАДА
  'bell canada', 'bell mobility', 'bell aliant',
  'rogers', 'rogers communications', 'rogers wireless',
  'telus', 'telus communications', 'telus mobility',
  'shaw', 'shaw communications',
  'videotron', 'videotron ltee',
  'freedom mobile', 'freedom canada',
  'sasktel', 'sasktel saskatchewan',
  'eastlink', 'eastlink canada',
  'teksavvy', 'teksavvy canada',

  // АВСТРАЛИЯ
  'telstra', 'telstra corporation', 'telstra australia',
  'optus', 'optus australia', 'singtel optus',
  'vodafone australia', 'vodafone au', 'vodafone hutchison',
  'tpg telecom', 'tpg australia',
  'aussie broadband', 'aussie bb',
  'iinet', 'iinet australia',
  'dodo', 'dodo australia',
  'internode', 'internode australia',
  'exetel', 'exetel australia',
  'superloop', 'superloop australia',

  // БРАЗИЛИЯ
  'vivo', 'vivo brazil', 'telefonica brasil',
  'claro', 'claro brasil', 'claro sa',
  'tim brasil', 'tim brazil', 'tim celular',
  'oi', 'oi brazil', 'oi sa',

  // МЕКСИКА
  'telcel', 'telcel mexico', 'radiomovil dipsa',
  'movistar mexico', 'movistar mx',
  'at&t mexico', 'at&t mx',
  'izzi', 'izzi mexico',
  'megacable', 'megacable mexico',
  'totalplay', 'totalplay mexico',

  // АФРИКА
  'vodacom', 'vodacom south africa', 'vodacom sa',
  'mtn', 'mtn south africa', 'mtn sa',
  'cell c', 'cell c south africa',
  'telkom sa', 'telkom south africa',
  'rain', 'rain south africa',
  'vodafone egypt', 'vodafone data',
  'orange egypt', 'orange eg',
  'etisalat egypt', 'etisalat eg',
  'telecom egypt', 'we egypt',
  'maroc telecom', 'maroc telecom morocco',
  'orange morocco', 'orange ma',
  'inwi', 'inwi morocco',
  'safaricom', 'safaricom kenya',
  'airtel kenya', 'airtel ke',
  'telkom kenya', 'telkom ke',

  // БЛИЖНИЙ ВОСТОК
  'bezeq', 'bezeq international',
  'partner', 'partner communications', 'orange israel',
  'cellcom', 'cellcom israel',
  'hot mobile', 'hot mobile israel',
  'pelephone', 'pelephone israel',
  'etisalat', 'etisalat uae', 'emirates telecom',
  'du', 'du uae', 'emirates integrated',
  'stc', 'stc saudi', 'saudi telecom',
  'mobily', 'mobily saudi',
  'zain saudi', 'zain ksa',
  'ooredoo qatar', 'ooredoo qa',
  'vodafone qatar', 'vodafone qa', 'vodafone qatar p.q.s.c',
  'ooredoo kuwait', 'ooredoo kw',
  'zain kuwait', 'zain kw',
  'stc kuwait', 'stc kw',

  // МОЛДОВА
  'orange moldova', 'orange md',
  'moldcell', 'moldcell moldova',
  'unite', 'unite moldova',
  'interdnestrcom', 'jscc interdnestrcom',

  // ГРУЗИЯ
  'new georgia', 'new georgia llc',
  'magticom', 'magticom georgia',
  'geocell', 'geocell georgia',
  'beeline georgia', 'veon georgia',

  // АРМЕНИЯ
  'beeline armenia', 'veon armenia',
  'vivacell', 'vivacell mts',
  'ucom', 'ucom armenia',

  // АЗЕРБАЙДЖАН
  'azercell', 'azercell telecom',
  'bakcell', 'bakcell azerbaijan',
  'azertelecom', 'azertelecom azerbaijan',
  'nar', 'nar mobile azerbaijan',

  // ПРИБАЛТИКА
  'telia latvia', 'telia lithuania',
  'bite', 'bite latvia', 'bite lithuania', 'bite-internet',
  'tet', 'tet latvia',
  'lmt', 'lmt latvia',
  'tele2 latvia', 'tele2 lithuania',
  'baltcom', 'baltcom latvia',
  'cgn', 'cgn latvia',
  'init', 'init latvia',

  // ДОПОЛНИТЕЛЬНЫЕ
  'nextgenwebs', 'nextgenwebs s.l.',
  'tigrisnet', 'tigrisnet iraq',
  'etihad atheeb telecom', 'etihad atheeb saudi',
  'ltd atelrybinsk', 'atelrybinsk',
];