// src/services/ProviderLists.ts - CLEAN VERSION WITH ONLY VERIFIED RESIDENTIAL ISP
export const VPN_KEYWORDS: string[] = [
  'nordvpn', 'nord vpn', 'nordsec', 'nord security',
  'expressvpn', 'express vpn', 'express technologies',
  'surfshark', 'surfshark vpn', 'surfshark ltd',
  'cyberghost', 'cyber ghost', 'cyberghost srl',
  'private internet access', 'pia vpn',
  'protonvpn', 'proton vpn', 'proton ag', 'proton technologies',
  'mullvad', 'mullvad vpn', 'mullvad vpn ab',
  'windscribe', 'windscribe limited',
  'hidemyass', 'hide my ass', 'hma vpn',
  'tunnelbear', 'tunnel bear',
  'hotspot shield', 'hotspotshield',
  'ipvanish', 'ip vanish',
  'vyprvpn', 'vypr vpn',
  'zenmate', 'zen mate',
  'betternet', 'better net',
  'psiphon', 'psiphon inc',
  'purevpn', 'pure vpn',
  'privatevpn', 'private vpn',
  'trust zone', 'trust.zone',
  'airvpn', 'air vpn',
  'azirevpn', 'azire vpn',
  'hide me', 'hide.me',
  'ivpn', 'ivpn limited',
  'ovpn', 'ovpn ab',
  'strongvpn', 'strong vpn',
  'torguard', 'tor guard',
  'vpn unlimited', 'keepsolid',
  'speedify', 'speedify inc',
  'ibvpn', 'nvpn', 'slickvpn',
  'seed4.me', 'seed4me',
  'vpnsecure', 'vpn secure',
  'ironsocket', 'iron socket',
  'cactusvpn', 'cactus vpn',
  'blackvpn', 'black vpn',
  'cryptostorm', 'crypto storm',
  'perfect privacy', 'perfect-privacy',
  'privado', 'privadovpn',
  'atlas vpn', 'atlasvpn',
  'urban vpn', 'urbanvpn',
  'hola vpn', 'holavpn',
  'touch vpn', 'touchvpn',
  'browsec', 'browsec vpn',
  'setupvpn', 'setup vpn',
  'turbo vpn', 'turbovpn',
  'secure vpn', 'securevpn',
  'fast vpn', 'fastvpn',
  'free vpn', 'freevpn',
  'super vpn', 'supervpn',
  'master vpn', 'mastervpn',
  'snap vpn', 'snapvpn',
  'thunder vpn', 'thundervpn',
  'flash vpn', 'flashvpn',
  'ultra vpn', 'ultravpn',
  'vpn hub', 'vpnhub',
  'vpn gate', 'vpngate',
  'vpn book', 'vpnbook',
  'vpn monster', 'vpnmonster',
  'vpn robot', 'vpnrobot',
  'x vpn', 'xvpn',
  'safervpn', 'safer vpn',
  'goose vpn', 'goosevpn',
  'anonvpn', 'anon vpn',
  'boxpn', 'box pn',
  'vpntunnel', 'vpn tunnel',
  'faceless.me', 'faceless me',
  'softether', 'softether vpn',
  'wireguard', 'wireguard vpn',
  'openvpn', 'openvpn inc',
  'vpnhero', 'vpn hero',
  'finevpn', 'fine vpn',
  'vpnlabs', 'vpn labs',
  'ivacy', 'ivacy vpn',
  'getflix', 'getflix vpn',
  'unlocator', 'unlocator vpn',
  'anonymizer', 'anonymizer inc',
  'hideme', 'hideme vpn',
  'switchvpn', 'switch vpn',
  'proxy.sh', 'proxy sh',
  'monstervpn', 'monster vpn',
  'smartdnsproxy', 'smart dns proxy',
  'vpn service', 'vpn provider', 'vpn network', 'vpn server', 'vpn node',
  'vpn exit', 'vpn tunnel', 'vpn gateway', 'vpn endpoint',
  'anonymous vpn', 'vpn anonymizer',
];

export const DATACENTER_KEYWORDS: string[] = [
  'equinix', 'equinix inc',
  'digital realty', 'digital realty trust',
  'cyrusone', 'cyrusone inc',
  'coresite', 'coresite realty',
  'interxion', 'interxion digital',
  'cogent', 'cogent communications',
  'level3', 'level3 communications',
  'datacenter', 'data center', 'data-centre', 'data centre',
  'datacamp', 'datacamp limited',
  'datapacket', 'datapacket limited',
  'm247', 'm247 europe', 'm247 limited',
  'ddos-guard', 'ddos-guard llc',
  'qrator', 'qrator labs',
  'serverius', 'serverius b.v.',
  'webtropia', 'webtropia gmbh',
  'myracloud', 'myracloud gmbh',
  'reliablesite', 'reliablesite llc',
  'webnx', 'webnx inc',
  'multacom', 'multacom corporation',
  'sentris', 'sentris network',
  'tier.net', 'tier net',
  'secured servers', 'secured servers llc',
  'ioflood', 'ioflood llc',
  'hivelocity', 'hivelocity inc',
  'constant.com', 'constant company',
  'steadfast', 'steadfast networks',
  'handy networks', 'handy networks llc',
  'performive', 'performive llc',
  'onlyservers', 'onlyservers llc',
  'server house', 'server house llc',
  'uk servers', 'uk servers ltd',
  'internet utilities', 'internet utilities na llc',
  'latitude.sh', 'latitude sh',
  'datashack', 'datashack llc',
  'colohouse', 'colohouse com',
  'coloserv', 'coloserv com',
  'gigenet', 'gigenet com',
  'globalfrag', 'globalfrag com',
  'flexential', 'flexential com',
  'evocative', 'evocative com',
  'drserver', 'drserver net',
  'quickpacket', 'quickpacket com',
  'dosarrest', 'dosarrest com',
  'ddos protection', 'ddos mitigation',
  'colo', 'colocation', 'colo hosting',
  'bare metal', 'bare-metal',
  'dedicated server', 'dedicated hosting',
  'iaas', 'paas', 'saas',
  'network infrastructure', 'infrastructure',
  'server farm', 'server cluster', 'server room',
  'colocation facility', 'colo facility',
  'rack space', 'rack unit', 'server rack',
  'hyperscale', 'hyper scale',
  'edge data center', 'edge facility',
  'modular data center', 'container data center',
  'green data center', 'sustainable data center',
];

export const PROXY_KEYWORDS: string[] = [
  'brightdata', 'bright data', 'luminati', 'luminati networks',
  'oxylabs', 'oxylabs proxy',
  'smartproxy', 'smart proxy',
  'geosurf', 'geosurf proxy',
  'netnut', 'netnut proxy',
  'soax', 'soax proxy',
  'iproyal', 'ip royal',
  'webshare', 'web share',
  'stormproxies', 'storm proxies',
  'myprivateproxy', 'my private proxy',
  'instantproxies', 'instant proxies',
  'sslprivateproxy', 'ssl private proxy',
  'highproxies', 'high proxies',
  'anonymous-proxy', 'anonymous proxy',
  'free-proxy', 'free proxy', 'freeproxy',
  'open proxy', 'public proxy',
  'shared proxy', 'private proxy', 'dedicated proxy',
  'rotating proxy', 'backconnect proxy',
  'residential proxy', 'residential vpn',
  'datacenter proxy', 'mobile proxy',
  'proxy-cheap', 'proxy cheap',
  'proxy-seller', 'proxy seller',
  'proxy-sale', 'proxy sale',
  'proxystore', 'proxy store',
  'marsproxies', 'mars proxies',
  'proxyrack', 'proxy rack',
  'rayobyte', 'rayobyte proxy',
  'dataimpulse', 'data impulse',
  'infatica', 'infatica proxy',
  'proxyempire', 'proxy empire',
  'mangoproxy', 'mango proxy',
  'ipnproxy', 'ipn proxy',
  'geonode', 'geonode proxy',
  'the social proxy', 'social proxy',
  'proxycompass', 'proxy compass',
  'nstproxy', 'nst proxy',
  'lumiproxy', 'lumi proxy',
  'proxyblocks', 'proxy blocks',
  'proxidize', 'proxidize proxy',
  'roundproxies', 'round proxies',
  'proxywing', 'proxy wing',
  'swiftproxy', 'swift proxy',
  'lightning proxies', 'lightning proxy',
  'socks5', 'socks4', 'socks proxy',
  'shadowsocks', 'shadowsocks proxy',
  'v2ray', 'v2ray proxy', 'v2fly',
  'trojan', 'trojan proxy', 'trojan-gfw',
  'xray', 'xray proxy', 'xray-core',
  'vmess', 'vless', 'vmess proxy', 'vless proxy',
  'hysteria', 'hysteria proxy',
  'naiveproxy', 'naive proxy',
  'sing-box', 'singbox',
  'proxy provider', 'proxy service', 'proxy store',
  'buy proxy', 'buy proxies',
  'cheap proxy', 'cheap proxies',
  'premium proxy', 'premium proxies',
  'elite proxy', 'elite proxies',
  'http proxy', 'https proxy', 'socks4 proxy', 'socks5 proxy',
  'ssl proxy', 'tls proxy',
  'cgi proxy', 'web proxy', 'php proxy',
  'forward proxy', 'reverse proxy',
  'open proxy list', 'free proxy list',
  'proxy list', 'proxylist',
  'proxies', 'proxys', 'proxy',
  'proxy server', 'proxy network', 'proxy chain', 'proxy tunnel',
  'proxy gateway', 'proxy endpoint', 'proxy node',
  'proxy pool', 'proxy rotator', 'proxy rotation',
  'proxy api', 'proxy dashboard', 'proxy panel',
  'proxy scraper', 'proxy checker', 'proxy tester',
  'proxy unblock', 'proxy bypass',
  'proxy sneaker', 'sneaker proxy',
  'proxy scraping', 'scraping proxy',
  'proxy mobile', 'mobile proxy', '4g proxy', '5g proxy',
  'proxy lte', 'lte proxy', '3g proxy', 'cellular proxy',
  'proxy isp', 'isp proxy', 'static isp proxy',
  'proxy residential', 'residential proxy',
  'proxy datacenter', 'datacenter proxy', 'server proxy',
  'proxy ipv4', 'ipv4 proxy', 'proxy ipv6', 'ipv6 proxy',
  'proxy dedicated', 'dedicated proxy', 'private proxy',
  'proxy shared', 'shared proxy',
  'proxy rotating', 'rotating proxy', 'sticky proxy',
  'proxy backconnect', 'backconnect proxy',
  'proxy reverse', 'reverse proxy',
];

export const HOSTING_KEYWORDS: string[] = [
  'digitalocean', 'digital ocean', 'digitalocean llc',
  'amazon web services', 'amazon aws', 'amazon data',
  'microsoft azure', 'azure cloud',
  'google cloud', 'gcp', 'google cloud platform',
  'oracle cloud', 'oracle corporation',
  'alibaba cloud', 'alibaba group',
  'tencent cloud', 'tencent computing',
  'ibm cloud', 'ibm corporation', 'softlayer',
  'baidu cloud', 'baidu',
  'huawei cloud', 'huawei technologies',
  'akamai', 'akamai technologies', 'akamai connected cloud',
  'cloudflare', 'cloudflare inc', 'cloudflare warp',
  'fastly', 'fastly inc',
  'linode', 'linode llc',
  'vultr', 'vultr holdings', 'vultr holdings llc',
  'ovh', 'ovh sas', 'ovh hosting', 'ovhcloud', 'ovh cloud',
  'hetzner', 'hetzner online', 'hetzner online gmbh',
  'choopa', 'choopa llc',
  'colocrossing', 'colocrossing solutions',
  'buyvm', 'buyvm llc',
  'ramnode', 'ramnode llc',
  'psychz', 'psychz networks',
  'quadranet', 'quadranet enterprises',
  'phoenixnap', 'phoenix nap',
  'leaseweb', 'leaseweb global',
  'online.net', 'online sas',
  'scaleway', 'scaleway sas',
  'contabo', 'contabo gmbh',
  'netcup', 'netcup gmbh',
  'strato', 'strato ag',
  'ionos', 'ionos se', '1&1 ionos',
  'hostwinds', 'hostwinds llc',
  'namecheap', 'namecheap hosting',
  'godaddy', 'godaddy hosting',
  'bluehost', 'bluehost inc',
  'hostgator', 'hostgator com',
  'siteground', 'siteground hosting',
  'dreamhost', 'dreamhost llc',
  'hostinger', 'hostinger international',
  'liquid web', 'liquid web llc',
  'wpengine', 'wp engine',
  'a2 hosting', 'a2 hosting inc',
  'greengeeks', 'greengeeks llc',
  'inmotion hosting', 'inmotion hosting inc',
  'aruba', 'aruba cloud',
  'krystal', 'krystal hosting',
  'interserver', 'interserver inc',
  'hostpapa', 'hostpapa inc',
  'hostmonster', 'hostmonster com',
  'justhost', 'justhost com',
  'fatcow', 'fatcow hosting',
  'ipage', 'ipage hosting',
  'hostodo', 'hostodo com',
  'hostus', 'hostus com',
  'hosteons', 'hosteons com',
  'hostnamaste', 'hostnamaste com',
  'hostcram', 'hostcram com',
  'hostdare', 'hostdare com',
  'hostkoala', 'hostkoala com',
  'hostarmada', 'hostarmada com',
  'hostdime', 'hostdime com',
  'hosthavoc', 'hosthavoc com',
  'hostkey', 'hostkey b.v.',
  'hosthatch', 'hosthatch inc',
  'nexusbytes', 'nexusbytes llc',
  'servarica', 'servarica inc',
  'liteserver', 'liteserver nl',
  'greencloud', 'greencloud llc',
  'anynode', 'anynode llc',
  'servercheap', 'servercheap inc',
  'cloudcone', 'cloudcone llc',
  'evolution hosting', 'evolution hosting llc',
  'maxkvm', 'maxkvm llc',
  'racknerd', 'racknerd llc',
  'melbicom', 'melbicom llc',
  'serverhino', 'serverhino llc',
  'vdsina', 'vdsina llc',
  'firstvds', 'firstvds llc',
  'ruvds', 'ruvds llc',
  'aeza', 'aeza group', 'aeza international',
  'timeweb', 'timeweb cloud',
  'beget', 'beget llc',
  'sprinthost', 'sprinthost llc',
  'reg.ru', 'reg.ru ltd',
  'nic.ru', 'nic.ru jsc',
  'masterhost', 'masterhost llc',
  'spaceweb', 'spaceweb llc',
  'webdock', 'webdock cloud',
  'dataforest', 'dataforest gmbh',
  'alexhost', 'alexhost srl',
  'axushost', 'axushost b.v.',
  'pq hosting', 'pqhosting',
  'it-grad', 'it grad',
  'fornex', 'fornex com',
  'vscale', 'vscale io',
  'king-servers', 'king servers',
  'cdn77', 'cdn77 com',
  'stackpath', 'stackpath llc',
  'keycdn', 'keycdn llc',
  'bunnycdn', 'bunnycdn llc',
  'cloudfront', 'amazon cloudfront',
  'vercel', 'vercel inc',
  'netlify', 'netlify inc',
  'fly.io', 'fly io',
  'render', 'render com',
  'railway', 'railway corp',
  'heroku', 'heroku inc',
  'edgecast', 'edgecast networks',
  'limelight', 'limelight networks',
  'chinacache', 'chinacache networks',
  'wangsu', 'wangsu science',
  'quantil', 'quantil networks',
  'vps', 'vds', 'dedicated server', 'dedicated hosting',
  'bare metal', 'bare-metal',
  'colocation', 'colo', 'colo hosting',
  'iaas', 'paas', 'saas',
  'server hosting', 'web hosting', 'game hosting',
  'shared hosting', 'reseller hosting', 'cloud hosting',
  'wordpress hosting', 'email hosting', 'dns hosting',
  'hosting', 'hosted', 'hosted by', 'hosted on',
  'cloud', 'cloud server', 'cloud hosting',
  'web server', 'webserver',
];

export const INSTANT_BAN_KEYWORDS: string[] = [
  ...VPN_KEYWORDS,
  ...DATACENTER_KEYWORDS,
  ...PROXY_KEYWORDS,
  ...HOSTING_KEYWORDS,
  'tor exit', 'tor node', 'tor relay', 'tor project', 'torservers',
  'tor exit node', 'tor bridge', 'tor network',
  'anonymous', 'anonymizer', 'anonymity',
  'hide my ip', 'hidemyip', 'hide ip',
  'mask ip', 'mask my ip', 'ip mask',
  'spoof ip', 'ip spoof', 'fake ip',
  'tunnel provider', 'tunnel service',
  'tunnel broker', 'tunnelbroker',
  'global layer', 'global-layer',
  'ipxo', 'ipxo llc',
  'packet exchange', 'packetexchange',
  'high volume network', 'high bandwidth',
  'network transit', 'transit provider',
  'bgp transit', 'bgp network',
  'internet exchange', 'internetexchange', 'ixp',
  'hosting provider', 'vpn provider', 'proxy provider',
  'antidetect', 'anti detect', 'multi login',
  'browser automation', 'web automation',
  'scraping service', 'scraping proxy',
  'sneaker proxy', 'sneaker bot',
  'residential network', 'p2p proxy',
  'p2p network', 'p2p vpn',
  'anycast', 'anycast network',
  'edge computing', 'edge network',
  'load balancer', 'loadbalancer',
  'reverse proxy', 'forward proxy',
  'dns hosting', 'dns provider',
  'domain hosting', 'domain registrar',
  'transparent proxy', 'transparent proxies',
  'cloud proxy', 'proxy api', 'proxy dashboard',
  'proxy pool', 'proxy rotator', 'proxy rotation',
  'dedicated cpu', 'shared cpu', 'high frequency',
  'block storage', 'object storage',
  'load balancing', 'auto scaling',
  'managed database', 'redis cloud',
  'mongodb atlas', 'postgres managed',
  'mysql hosting', 'mariadb hosting',
];

export const TRUSTED_PROVIDERS: string[] = [
  'kyivstar', 'kievstar',
  'vodafone ukraine', 'vodafone ua',
  'lifecell', 'lifecell ukraine',
  'ukrtelecom', 'jsc ukrtelecom',
  'lanet', 'lanet network',
  'triolan', 'triolan ukraine',
  'deutsche telekom', 'deutsche telekom ag', 'telekom deutschland',
  'vodafone germany', 'vodafone de',
  'vodafone uk', 'vodafone italy', 'vodafone spain',
  'vodafone portugal', 'vodafone turkey', 'vodafone egypt',
  'orange', 'orange france', 'orange poland',
  'orange spain', 'orange belgium', 'orange moldova',
  'orange egypt', 'orange morocco',
  'sfr', 'sfr sa',
  'bouygues', 'bouygues telecom',
  'free mobile', 'free sas', 'free mobile sas',
  'telefonica', 'movistar', 'o2 germany',
  'telenor', 'telenor as', 'telenor norge', 'telenor sweden',
  'telia', 'telia company', 'telia sweden',
  'telia finland', 'telia norway',
  'elisa', 'elisa oyj', 'elisa finland',
  'dna', 'dna oy', 'dna finland',
  'swisscom', 'swisscom ag',
  'proximus', 'proximus nv',
  'kpn', 'kpn b.v.', 'kpn telecom',
  'bt group', 'bt plc', 'british telecom',
  'ee limited', 'ee uk',
  'sky uk', 'sky broadband',
  'virgin media', 'virgin media uk',
  'talktalk', 'talktalk telecom',
  'plusnet', 'plusnet plc',
  'comcast', 'comcast cable', 'xfinity',
  'charter', 'charter communications', 'spectrum',
  'cox', 'cox communications',
  'at&t', 'verizon',
  'bell canada', 'bell mobility',
  'rogers', 'rogers communications',
  'telus', 'telus communications',
  'shaw', 'shaw communications',
  'telstra', 'telstra corporation',
  'optus', 'optus australia',
  'jio', 'reliance jio',
  'airtel', 'bharti airtel',
  'china telecom', 'china unicom', 'china mobile',
  'sk telecom', 'sk broadband',
  'kt corporation', 'lg uplus',
  'turk telekom', 'turk telekomunikasyon',
  'turkcell',
  'bezeq', 'bezeq international',
  'partner', 'partner communications',
  'etisalat', 'etisalat uae',
  'stc', 'saudi telecom',
  'vodacom', 'mtn', 'telkom sa',
  'vivo', 'vivo brazil',
  'claro', 'claro brasil',
  'telcel', 'telcel mexico',
  'movistar mexico',
  'rostelecom', 'mts', 'beeline', 'megafon',
  'beltelecom', 'byfly',
  'kazakhtelecom',
  'telenet', 'telenet nv',
  'voo', 'edpnet',
  'sunrise', 'sunrise switzerland',
  'salt', 'salt switzerland',
  'fastweb', 'fastweb spa',
  'iliad', 'iliad italia',
  'masmovil', 'euskaltel', 'jazztel',
  'yoigo', 'pepephone',
  'meo', 'meo portugal',
  'nos', 'nos comunicacoes',
  'nowo',
  'play', 'p4 sp',
  'plus poland', 'polkomtel',
  'vectra', 'netia',
  'turknet', 'turknet iletisim',
  'superonline', 'millenicom',
  'tele2 sweden', 'tele2 ab',
  'com hem', 'bahnhof', 'bredband2',
  'bsnl', 'bsnl india',
  'mtnl',
  'vodafone idea', 'vi india',
  'act fibernet', 'hathway', 'excitel',
  'zen internet', 'gigaclear', 'hyperoptic',
  'tiscali', 'tiscali italia',
  'eolo', 'linkem',
  'altibox', 'lyse',
  'ice norway', 'get norway',
  'eastlink', 'teksavvy', 'sasktel',
  'aussie broadband', 'iinet', 'dodo',
  'internode', 'exetel', 'superloop',
  'cell c', 'rain',
  'safaricom', 'airtel kenya', 'telkom kenya',
  'maroc telecom', 'inwi',
  'mobily', 'zain', 'ooredoo',
  'azercell', 'bakcell', 'azertelecom', 'nar',
  'magticom', 'geocell', 'beeline georgia',
  'beeline armenia', 'vivacell', 'ucom',
  'orange moldova', 'moldcell', 'unite',
  'bite', 'tet', 'lmt', 'baltcom',
];